[package]
name = "block-decomposition"
description = "Rust implementation of mahjong hand decomposition"
version = "0.1.0"
authors = ["Apricot S."]
edition = "2024"
rust-version = "1.90"
license = "MIT-0"
publish = false
readme = "README.md"
repository = "https://github.com/Apricot-S/block-decomposition"
keywords = ["mahjong", "riichi"]
categories = ["algorithms"]

[lints.rust]
warnings = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
unreadable_literal = "allow"
